"""Meta-Labeling filter -- second-pass ML model to approve/reject trading signals.

Architecture:
    MTF_MACD generates signal (LONG/SHORT) -> MetaLabeler predicts P(profit|features)
    -> if confidence > threshold: APPROVE and execute
    -> else: REJECT (downgrade to FLAT)

Training:
    Run MTF_MACD backtest on historical data -> collect signals with features and
    outcomes (win/loss) -> train XGBoost binary classifier -> deploy as filter.

Config (config["meta_labeling"]):
    enabled: true
    model: "xgboost"
    training_samples: 1000
    min_confidence: 0.55
"""

import pandas as pd
import numpy as np
from loguru import logger

from .base import Signal


class MetaLabeler:
    """XGBoost-based binary filter for trading signals.

    Does NOT inherit from BaseStrategy -- this is a filter, not a strategy.
    Takes a strategy's output (LONG/SHORT) and either approves or rejects it.

    Usage:
        labeler = MetaLabeler(config)
        labeler.train(trades_with_features)       # offline training
        ...
        if signal != FLAT:
            if labeler.evaluate(signal, features):
                execute(signal)
    """

    def __init__(self, config: dict):
        ml_cfg = config.get("meta_labeling", {})
        self.enabled = ml_cfg.get("enabled", True)
        self.min_confidence = ml_cfg.get("min_confidence", 0.58)  # Production: 0.58 (conservative)
        self.training_samples = ml_cfg.get("training_samples", 1000)
        self.max_features = ml_cfg.get("max_features", 30)  # Top-N features only (0 = all)

        # Model state
        self.model = None
        self._feature_names: list[str] = []
        self._trained = False
        self._train_samples = 0
        self._train_accuracy = 0.0

        # XGBoost params (conservative to avoid overfitting)
        self._model_params = {
            "n_estimators": 100,
            "max_depth": 4,
            "learning_rate": 0.03,
            "subsample": 0.8,
            "colsample_bytree": 0.7,
            "reg_alpha": 2.0,
            "reg_lambda": 3.0,
            "random_state": 42,
            "eval_metric": "logloss",
        }

        logger.info(
            f"MetaLabeler init: enabled={self.enabled} | "
            f"min_confidence={self.min_confidence} | "
            f"training_samples={self.training_samples}"
        )

        # Try to load pre-trained production model
        self._load_pretrained()

    # ─── Public API ────────────────────────────────────────────

    def is_ready(self) -> bool:
        """Returns True if the model is trained and ready to filter signals."""
        return self._trained and self.model is not None

    def evaluate(self, signal: Signal, features: dict) -> bool:
        """Evaluate a trading signal. Returns True to approve, False to reject.

        Args:
            signal: The Signal (LONG or SHORT) generated by the primary strategy.
            features: Feature dict from FeatureEngine at the moment of signal.

        Returns:
            True if the signal passes the meta-labeling filter.
        """
        if not self.is_ready():
            return True  # Pass-through when model not ready

        try:
            prob = self._predict(features)
            return prob >= self.min_confidence
        except Exception as e:
            logger.debug(f"MetaLabeler.evaluate error: {e} -- passing signal")
            return True  # Fail-open: don't block signals on prediction errors

    def train(self, trades: list[dict]) -> bool:
        """Train the meta-labeling model on historical trade data.

        Each trade dict must contain:
            - features_at_signal: dict of feature values at signal generation time
            - pnl: realized PnL for the trade (positive = win)
            - signal_type: "LONG" or "SHORT" (optional, adds as feature)

        Args:
            trades: List of trade dicts from a backtest run.

        Returns:
            True if training succeeded, False otherwise.
        """
        if not trades:
            logger.warning("MetaLabeler.train: no trades provided -- skipping")
            return False

        # 1. Build feature matrix and target
        X_rows = []
        y_rows = []

        for t in trades:
            feats = t.get("features_at_signal")
            if not feats or not isinstance(feats, dict):
                continue

            row = dict(feats)
            # Add signal type as a feature (LONG=1, SHORT=-1)
            signal_type = t.get("signal_type", "LONG")
            row["signal_is_long"] = 1.0 if signal_type == "LONG" else 0.0
            row["signal_is_short"] = 1.0 if signal_type == "SHORT" else 0.0

            X_rows.append(row)
            y_rows.append(1.0 if t.get("pnl", 0.0) > 0 else 0.0)

        if len(X_rows) < 50:
            logger.warning(f"MetaLabeler.train: only {len(X_rows)} valid samples (< 50) -- skipping")
            return False

        X = pd.DataFrame(X_rows)
        y = pd.Series(y_rows)

        # 2. Clean data
        X = X.replace([np.inf, -np.inf], np.nan).fillna(0)
        y = y.dropna()
        X = X.loc[y.index]

        # 3. Feature selection (if max_features is set and we have more features)
        if self.max_features and self.max_features > 0 and len(X.columns) > self.max_features:
            # Quick model to get feature importance
            import xgboost as xgb
            quick_model = xgb.XGBClassifier(
                n_estimators=50, max_depth=3, learning_rate=0.05,
                reg_alpha=1.0, reg_lambda=2.0, random_state=42
            )
            quick_model.fit(X.iloc[:-max(10, len(X)//5)], y.iloc[:-max(10, len(X)//5)])
            imp = quick_model.get_booster().get_score(importance_type="gain")
            top_features = sorted(imp, key=imp.get, reverse=True)[:self.max_features]
            X = X[top_features]
            logger.info(f"Feature selection: kept top {len(top_features)}/{len(imp)} features")

        # 4. Chronological split (80/20) for early stopping
        n_val = max(10, int(len(X) * 0.2))
        X_train, X_val = X.iloc[:-n_val], X.iloc[-n_val:]
        y_train, y_val = y.iloc[:-n_val], y.iloc[-n_val:]

        # 5. Train XGBoost
        try:
            import xgboost as xgb

            model = xgb.XGBClassifier(**self._model_params)
            fit_kwargs = {}
            if len(X_val) > 10:
                fit_kwargs["eval_set"] = [(X_val, y_val)]
                fit_kwargs["verbose"] = False
            model.fit(X_train, y_train, **fit_kwargs)

            self.model = model
            self._feature_names = list(X.columns)
            self._trained = True
            self._train_samples = len(X_train)

            # Evaluate on validation set
            y_pred = model.predict(X_val)
            self._train_accuracy = (y_pred == y_val).mean()

            # Feature importance (top 5)
            try:
                imp = model.get_booster().get_score(importance_type="gain")
                top5 = sorted(imp.items(), key=lambda x: x[1], reverse=True)[:5]
                top5_str = ", ".join(f"{k}={v:.0f}" for k, v in top5)
            except Exception:
                top5_str = "N/A"

            logger.info(
                f"MetaLabeler trained: {len(X_train)} samples, "
                f"{len(self._feature_names)} features, "
                f"val_accuracy={self._train_accuracy:.2f}, "
                f"class_balance={y.mean():.2f} | Top5: {top5_str}"
            )
            return True

        except Exception as e:
            logger.error(f"MetaLabeler.train failed: {e}")
            return False

    # ─── Internal ──────────────────────────────────────────────

    def _load_pretrained(self):
        """Load pre-trained model from models/meta_labeler_production.pkl if available."""
        import os, pickle
        model_path = os.path.join(os.path.dirname(__file__), "..", "models", "meta_labeler_production.pkl")
        if not os.path.exists(model_path):
            logger.info("No pre-trained MetaLabeler model found — will train from live data")
            return
        try:
            with open(model_path, "rb") as f:
                data = pickle.load(f)
            if data is None or not isinstance(data, dict):
                return
            self.model = data["model"]
            self._feature_names = data["feature_names"]
            self._trained = True
            self._train_samples = data.get("train_samples", 0)
            self._train_accuracy = data.get("val_accuracy", 0.0)
            # Restore config from saved model
            saved_cfg = data.get("config", {})
            self.min_confidence = saved_cfg.get("min_confidence", self.min_confidence)
            self._model_params.update(saved_cfg.get("model_params", {}))
            logger.info(
                f"Loaded pre-trained MetaLabeler: {self._train_samples} samples, "
                f"{len(self._feature_names)} features, val_acc={self._train_accuracy:.3f}, "
                f"trained={data.get('trained_at', 'unknown')}"
            )
        except Exception as e:
            logger.warning(f"Failed to load pre-trained MetaLabeler: {e} — will train from live data")

    def _predict(self, features: dict) -> float:
        """Predict probability that a signal will be profitable.

        Returns probability in [0, 1]. Returns 0.5 on prediction failure.
        """
        if self.model is None:
            return 0.5

        try:
            # Build aligned feature row
            row = {k: features.get(k, 0.0) for k in self._feature_names}
            X = pd.DataFrame([row])
            X = X.replace([np.inf, -np.inf], np.nan).fillna(0)

            # Ensure all expected columns present
            for col in self._feature_names:
                if col not in X.columns:
                    X[col] = 0.0

            proba = self.model.predict_proba(X[self._feature_names])
            return float(proba[0, 1]) if proba.shape[1] > 1 else 0.5

        except Exception as e:
            logger.debug(f"MetaLabeler._predict error: {e}")
            return 0.5

    # ─── Degradation Monitoring ───────────────────────────────

    def record_outcome(self, approved: bool, was_profitable: bool):
        """Record the outcome of a meta-labeling decision for degradation tracking.

        Call this AFTER a trade closes (or when a rejected signal would have closed).

        Args:
            approved: True if the signal passed the meta-labeler filter.
            was_profitable: True if the trade (or would-be trade) was profitable.
        """
        if not hasattr(self, '_outcome_log'):
            self._outcome_log: list[dict] = []
        import time
        self._outcome_log.append({
            "ts": int(time.time()),
            "approved": approved,
            "win": was_profitable,
        })
        # Keep last 500 outcomes
        if len(self._outcome_log) > 500:
            self._outcome_log = self._outcome_log[-500:]

    def rolling_wr(self, n: int = 50) -> float:
        """Win rate of last N accepted trades (None if insufficient data)."""
        if not hasattr(self, '_outcome_log'):
            return None
        accepted = [e for e in self._outcome_log if e["approved"]]
        if len(accepted) < n:
            return None
        recent = accepted[-n:]
        return sum(1 for e in recent if e["win"]) / n

    def monthly_sharpe(self) -> float:
        """Approximate monthly Sharpe of accepted trades (None if insufficient data)."""
        if not hasattr(self, '_outcome_log'):
            return None
        import time
        now = int(time.time())
        month_ago = now - 30 * 86400
        month_trades = [e for e in self._outcome_log
                        if e["approved"] and e["ts"] >= month_ago]
        if len(month_trades) < 5:
            return None
        wins = sum(1 for e in month_trades if e["win"])
        losses = len(month_trades) - wins
        wr = wins / len(month_trades) if month_trades else 0
        # Rough Sharpe from WR assuming avg_win ≈ avg_loss
        if wr > 0 and wr < 1:
            return (wr - 0.5) / (wr * (1 - wr)) ** 0.5 * (len(month_trades) ** 0.5) / 2
        return 0.0

    def check_degradation(self) -> list[str]:
        """Check for degradation. Returns list of active alerts (empty = healthy)."""
        alerts = []
        wr50 = self.rolling_wr(50)
        ms = self.monthly_sharpe()

        if wr50 is not None and wr50 < 0.60:
            alerts.append(f"ROLLING_WR_DEGRADED: 50-trade WR={wr50:.1%} < 60%")
        if ms is not None and ms < 2.0:
            alerts.append(f"MONTHLY_SHARPE_LOW: monthly Sharpe={ms:.2f} < 2.0")

        # Check 2 consecutive months
        if hasattr(self, '_outcome_log') and len(self._outcome_log) >= 100:
            import time
            now = int(time.time())
            m1_trades = [e for e in self._outcome_log
                         if e["approved"] and now - 60*86400 <= e["ts"] < now - 30*86400]
            m2_trades = [e for e in self._outcome_log
                         if e["approved"] and e["ts"] >= now - 30*86400]
            if len(m1_trades) >= 5 and len(m2_trades) >= 5:
                wr1 = sum(1 for e in m1_trades if e["win"]) / len(m1_trades)
                wr2 = sum(1 for e in m2_trades if e["win"]) / len(m2_trades)
                # Approximate Sharpe
                def approx_sharpe(wr, n):
                    if wr <= 0 or wr >= 1 or n < 2:
                        return 0
                    return (wr - 0.5) / (wr * (1 - wr)) ** 0.5 * (n ** 0.5) / 2
                s1 = approx_sharpe(wr1, len(m1_trades))
                s2 = approx_sharpe(wr2, len(m2_trades))
                if s1 < 2.0 and s2 < 2.0:
                    alerts.append(f"CONSECUTIVE_MONTHLY_SHARPE_LOW: {s1:.1f}/{s2:.1f} < 2.0 for 2 months")

        return alerts

    # ─── Diagnostics ───────────────────────────────────────────

    def get_diagnostics(self) -> dict:
        """Return current model state for logging or dashboard."""
        wr50 = self.rolling_wr(50)
        return {
            "trained": self._trained,
            "model_type": "xgboost" if self.model is not None else "none",
            "training_samples": self._train_samples,
            "features_used": len(self._feature_names),
            "val_accuracy": round(self._train_accuracy, 3),
            "min_confidence": self.min_confidence,
            "rolling_wr_50": round(wr50, 3) if wr50 is not None else None,
            "alerts": self.check_degradation(),
        }
